Tutorials
tzamalisp/crossai pull request #10
Opened 2023-11-20 08:54 UTC by gkontogiannhs

2023-11-20 09:16 UTC, CaptainAlready commented
The tutorials contain many errors which are also printed and increase the file size.
Could some prints also be reduced to decrease the size of the tutorial notebooks?
Also, in my opinion the tutorial notebooks are too many (1 - 2  small tutorials would suffice)

2023-11-20 09:30 UTC, tzamalisp commented
> The tutorials contain many errors which are also printed and increase the file size. Could some prints also be reduced to decrease the size of the tutorial notebooks? Also, in my opinion the tutorial notebooks are too many (1 - 2 small tutorials would suffice)

@CaptainAlready we are under development progress here. Therefore, we will take into account all the possible ways to reduce the tutorials' file size. According to the number of tutorials, we are designing with @gkontogiannhs which will be the best way for the user to understand how the lib works.

2023-11-21 09:13 UTC, gkontogiannhs commented
Thank you, @CaptainAlready, for your feedback. The Tutorials branch aims to assess the robustness of the library in its initial phase. Through this, we'll explore potential feature redesigns to enhance user-friendliness, followed by optimizations for size, clarity, and overall efficiency. Regarding errors, some were intentionally left unaddressed due to lack of data in certain cases. Rest assured, these issues will be promptly resolved.

2023-11-27 07:49 UTC, pep8speaks commented
Hello @gkontogiannhs! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





















* In the file [`tutorials/utils.py`](https://github.com/tzamalisp/crossai/blob/0c63f8e36df7333f02128492ccae5faa17af6576/tutorials/utils.py):

> [Line 29:48](https://github.com/tzamalisp/crossai/blob/0c63f8e36df7333f02128492ccae5faa17af6576/tutorials/utils.py#L29): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 34:65](https://github.com/tzamalisp/crossai/blob/0c63f8e36df7333f02128492ccae5faa17af6576/tutorials/utils.py#L34): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 36:1](https://github.com/tzamalisp/crossai/blob/0c63f8e36df7333f02128492ccae5faa17af6576/tutorials/utils.py#L36): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace



##### Comment last updated at 2023-11-29 16:58:01 UTC

2023-11-27 17:19 UTC, tzamalisp commented
## Configuration

in the following lines https://github.com/tzamalisp/crossai/blob/57c661e6e072e585d63b6b020b162dcb27d4a0b2/tutorials/config_loader.py#L4-L13

* add properly the "Loads configuration from.." next to the `"""`

## Audio Speech Commands Recognition

in the lines

```
os.environ["CUDA_VISIBLE_DEVICES"] = "2"
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"
```
add the level to the configuration file.

in `DATASET_PATH = config['PATH']['MINI_SPEECH_COMMANDS']`, please define how the user should load the data properly (audio data in classes, link to the README)

why this one is in comment: `# tf.keras.utils.plot_model(cnn1d, to_file='Simple-CNN1D.png', show_shapes=True)`

the next one could go to a `utils` script:

```
def plot_learning(history):
    metrics = history.history
    history_keys = list(history.history.keys())
    plt.figure(figsize=(16, 6))
    plt.subplot(1, 2, 1)
    plt.plot(history.epoch, metrics[history_keys[0]], metrics[history_keys[2]])
    plt.legend(['loss', 'val_loss'])
    plt.ylim([0, max(plt.ylim())])
    plt.xlabel('Epoch')
    plt.ylabel('Loss [CrossEntropy]')

    plt.subplot(1,2,2)
    plt.plot(history.epoch, 100*np.array(metrics[history_keys[1]]), 100*np.array(metrics[history_keys[3]]))
    plt.legend(['accuracy', 'val_accuracy'])
    plt.ylim([0, 100])
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy [%]')
```

2023-11-27 17:29 UTC, tzamalisp commented
@gkontogiannhs @fothot2 

## Motion Recognition E2E

* In cell 11, I would add only once the `TimeMeasurementWrapper`, to show the functionality.  I would also explain what it does in a few words in the markdown.

* the `plot_ts` could export two subplots so the y-axis is depicted properly in case of a huge difference between the range of values of the different time series.

* the `batch_evaluate` should count and indicate the instance that it processes each time.

2023-11-27 17:32 UTC, tzamalisp requested changes

2023-11-27 17:32 UTC, tzamalisp commented on tutorials/config_loader.py
> +    """
add properly the "Loads configuration from.." next to the """

2023-11-29 16:59 UTC, merged