pep8 and docstring
tzamalisp/crossai pull request #16
Opened 2023-11-22 13:17 UTC by gkontogiannhs

2023-11-23 10:45 UTC, pep8speaks commented
Hello @gkontogiannhs! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`crossai/ai/nn1d/_bilstm_time.py`](https://github.com/tzamalisp/crossai/blob/8aa989179fa9d7488484a3d60ea4eb58a2266155/crossai/ai/nn1d/_bilstm_time.py):

> [Line 37:80](https://github.com/tzamalisp/crossai/blob/8aa989179fa9d7488484a3d60ea4eb58a2266155/crossai/ai/nn1d/_bilstm_time.py#L37): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 39:80](https://github.com/tzamalisp/crossai/blob/8aa989179fa9d7488484a3d60ea4eb58a2266155/crossai/ai/nn1d/_bilstm_time.py#L39): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)

2023-11-27 14:55 UTC, tzamalisp commented
@gkontogiannhs I suggest the following changes in all the AI modeling parts, in general:
* In some arguments, the description starts in lowercase while it should be in uppercase
* We should say, "An integer that represents the number of filters..." instead of "Number of filters...."
* When we describe the function, the description should start after the `"""` characters and not in the next line. Please, be careful with the indentation. There is no consistency in the way of writing.
* Check where the parentheses indentation when closing def's arguments
* We proposed in the meeting that the docstring will include the papers' links.


Check this example

```
def fetch_smalltable_rows(
    table_handle: smalltable.Table,
    keys: Sequence[bytes | str],
    require_all_keys: bool = False,
) -> Mapping[bytes, tuple[str, ...]]:
    """Fetches rows from a Smalltable.

    Retrieves rows pertaining to the given keys from the Table instance
    represented by table_handle.  String keys will be UTF-8 encoded.

    Args:
        table_handle: An open smalltable.Table instance.
        keys: A sequence of strings representing the key of each table
          row to fetch.  String keys will be UTF-8 encoded.
        require_all_keys: If True only rows with values set for all keys will be
          returned.

    Returns:
        A dict mapping keys to the corresponding table row data
        fetched. Each row is represented as a tuple of strings. For
        example:

        {b'Serak': ('Rigel VII', 'Preparer'),
         b'Zim': ('Irk', 'Invader'),
         b'Lrrr': ('Omicron Persei 8', 'Emperor')}

        Returned keys are always bytes.  If a key from the keys argument is
        missing from the dictionary, then that row was not found in the
        table (and require_all_keys must have been False).

    Raises:
        IOError: An error occurred accessing the smalltable.
    """

```

2023-11-27 15:27 UTC, tzamalisp requested changes

2023-11-27 15:27 UTC, tzamalisp commented on crossai/ai/nn1d/_bilstm_time.py
>      This model converts low-level audio features into high-level expressions.
@gkontogiannhs only audio? I think we have to say "time series"?

2023-11-27 15:27 UTC, tzamalisp commented on crossai/ai/nn1d/_bilstm_time.py
>      """Constructs a deep neural network using bidirectional LSTM.
@gkontogiannhs -> LSTM (BiLSTM) layers

2023-11-27 15:27 UTC, tzamalisp commented on crossai/ai/_layers_dropout.py
> +    Monte Carlo Dropout layer.
@gkontogiannhs add how it works at a high level (also in the next functions). Also, describe why we add these layers, except for using them for model generalization (e.g., prediction -> measuring robustness)

2023-11-27 15:27 UTC, tzamalisp commented on crossai/ai/nn1d/_xceptiontime.py
> -        A Keras Model instance.
@gkontogiannhs  a Keras or TensorFlow?

2023-11-27 15:27 UTC, tzamalisp commented on crossai/ai/nn1d/_xceptiontime.py
>      """Create a block of layers consisting of Conv1D, BatchNormalization,
@gkontogiannhs Creates...

2023-11-27 15:27 UTC, tzamalisp commented on crossai/ai/nn2d/_resnet34.py
> +    Constructs a ResNet34 model suitable for image classification tasks.
@gkontogiannhs This should be in the line above -> """Constructs..

2023-11-27 15:27 UTC, tzamalisp commented on crossai/ai/nn1d/_bilstm_time.py
> +def dense_block(inputs: tf.Tensor, n_layers: int, dense_units: list):
@gkontogiannhs split in different lines

2023-11-27 15:27 UTC, tzamalisp commented on crossai/ai/nn1d/_xceptiontime.py
>      """Xception Block function that applies a series of Xception modules,
@gkontogiannhs Xception Block function that --> remove that one. We say "Applies a..."

2023-11-27 15:27 UTC, tzamalisp commented on crossai/ai/nn1d/_xceptiontime.py
>      """XceptionModule function that applies a series of SeparableConv1D layers
@gkontogiannhs "Applies the Xception module which is a series...."

2023-11-28 14:51 UTC, gkontogiannhs commented on crossai/ai/nn1d/_bilstm_time.py
>      """Constructs a deep neural network using bidirectional LSTM.
Returned value is a keras model.

2023-12-18 16:44 UTC, merged